### PR TITLE
Change access modifiers to allow custom gesture recognisers

### PR DESCRIPTION
**Pull request by adipascu**
We have opened up the api for extension, we currently have in use a custom gesture recognizer that is not in the `it.sephiroth.android.library.uigestures` package.

### CODE REVIEW

**Comment by sephiroth74** [comment]
It's the same as https://github.com/sephiroth74/AndroidUIGestureRecognizer/pull/8. I just don't see the point in having "inState" method to be public

**Comment by adipascu** [comment]
It is in use in gesture recognisers that may be in different packages, for example 

https://github.com/sephiroth74/AndroidUIGestureRecognizer/blob/09ead303b2fc9a8da6bbc8572a4f726411893537/uigesturerecognizer/src/main/java/it/sephiroth/android/library/uigestures/UISwipeGestureRecognizer.java#L338

**Comment by adipascu** [comment]
Thanks for merging !

**Comment by sephiroth74** [comment]
thank you for the contribution!

**Pull request merged**
